### ISSUE TITLE
Вопросы: JS: tasks/micro-tasks: 1

### ISSUE THREAD

**Issue by kicumkicum** [vova-learn/js-labs#1]
Что будет в консоли и почему?

```js
console.log(1);

setTimeout(() => console.log(2), 0);

Promise.resolve().then(() => console.log(3));

console.log(4);
```

**Comment by vova-learn** [comment]
`1 → 4 → 2 → 3 // не проверял в консоли
`
Реализация следующая: event loop в браузере работает в асинхронном режиме, т.е. задача одна за одной формируя стэк задач. Если задача должна выполниться сейчас - он её передаёт в работу и ждёт выполнения. Если задача отложенная - передаёт в работу в стэк отложенных задач, предоставляется сторонним API (но это не точно), который следит за их выполнением. В стэеке отоложенных задач есть разделение на микро и макро задачи, могу предположить, что если завести тайм-аут в рэзолве - выполнение промиса будет ждать таймаут, поэтому промим, - это микро задача, а таймаут - макро.

**Comment by vova-learn** [comment]
Погуглил, вроде всё верно описал, только перепутал приоритет, он у микро-задач выше, чем у макро-задач. Поэтому результат:
`1 → 4 → 3 → 2`

**Comment by vova-learn** [comment]
Норм статья - https://russianblogs.com/article/3184228338/

**Comment by kicumkicum** [comment]
А какие ещё операции относятся к микро и макро задачам?

**Comment by vova-learn** [comment]
Попытался разобраться и вот к чему пришел: 
- все асинхронные задачи, которые обрабатываются в рамках колстэка и предоставленные v8 - микрозадачи (асинхронные обработчики промиса - then/.catch/.finally); 
- все асинхронные задачи, которые предоставляются от WebAPI являются макрозадачами (DOM-события, XMLHTTPRequest, таймеры), они имеют меньший приоритет и выполняются по своему механизму, и будут выполнены только после очистки очереди.
