### ISSUE TITLE
Вопросы: JS: variables: 1

### ISSUE THREAD

**Issue by kicumkicum** [vova-learn/js-labs#2]
Что будет в консоли и почему?

```js
let foo = {n: 11};
let bar = foo;

bar = {};

console.log(foo);
```

**Comment by vova-learn** [comment]
```
let foo = {n: 11}; // ссылка на {n: 11}
let bar = foo; // ссылка на {n: 11}

bar = {}; // не знаю, как правильно описать, вообщем, перепишет объект на который ссылается bar

console.log(foo); // {}
```

**Comment by vova-learn** [comment]
Cложные типы данных - Объекты, они передаются по ссылке. По факту при определении переменной браузер читает код справа налево, т.е. сначала определяет значение, а потом присваивает его переменной. При объявлении сложного типа создаётся объект наследник глобального Object, и в качестве пути к этому объекту будет выступать заданная переменная, т.е. она хранит только путь, а не само значение объекта.

**Comment by kicumkicum** [comment]
> ```
> let foo = {n: 11}; // ссылка на {n: 11}
> let bar = foo; // ссылка на {n: 11}
> 
> bar = {}; // не знаю, как правильно описать, вообщем, перепишет объект на который ссылается bar
> 
> console.log(foo); // {}
> ```

Выполни код. Посмотри так ли это на самом деле.

**Comment by kicumkicum** [comment]
> Cложные типы данных - Объекты, они передаются по ссылке. По факту при определении переменной браузер читает код справа налево, т.е. сначала определяет значение, а потом присваивает его переменной. При объявлении сложного типа создаётся объект наследник глобального Object, и в качестве пути к этому объекту будет выступать заданная переменная, т.е. она хранит только путь, а не само значение объекта.

Ты все правильно говоришь, только лучше использовать понятие 'ссылка', а не 'путь'

**Comment by vova-learn** [comment]
> > ```
> > let foo = {n: 11}; // ссылка на {n: 11}
> > let bar = foo; // ссылка на {n: 11}
> > 
> > bar = {}; // не знаю, как правильно описать, вообщем, перепишет объект на который ссылается bar
> > 
> > console.log(foo); // {}
> > ```
> 
> Выполни код. Посмотри так ли это на самом деле.

Ага, я понял.
