### ISSUE TITLE
Вопросы: React: hooks: 1

### ISSUE THREAD

**Issue by kicumkicum** [vova-learn/js-labs#6]
Зачем появились хуки в реакте? Какая их задача?

**Comment by vova-learn** [comment]
Для того, чтобы упростить порог входа и уйти от классов, и подвязки под контекст.  Они позволяют расширить функционал функциональных компонентов.

**Comment by kicumkicum** [comment]
А в чем заключается уменьшение порога входа?

**Comment by vova-learn** [comment]
Может из-за перехода с объектно-ориентированного на функциональное программирование.

**Comment by kicumkicum** [comment]
В целом да. Но если углубиться, то в классовом компоненте методы жизненного цикла разрозненны и могут быть описаны в любом порядке. Из-за этого читать и понимать их немного сложно.

В функциональном компоненте код читается сверху вниз и это немного упрощает понимание того, что происходит.

Немного - потому что если увлечься, то у тебя образуется много хуков и сложность опять возвращается, но другая - у тебя все лежит в одной куче. Поэтому серебрянной пули как таковой нет. У всего свои плюсы и минусы, как и у всего в программировании.
