### ISSUE TITLE
Вопросы: JS: Таймеры: 1

### ISSUE THREAD

**Issue by kicumkicum** [vova-learn/js-labs#8]
В чем отличие `setTimeout` и `setInterval`?

Когда они применяются?

Как можно их отменить?

**Comment by vova-learn** [comment]
_В чем отличие setTimeout и setInterval?_

Методы-таймеры предоставленные WebAPI. Они асинхронны и выполняются как макро-задачи. Оба метода принимают в качестве параметров функцию и время задержки выполнения. `setTimeout` - выполняет указанную функцию **один раз через заданное время**.   `setTimeout` - выполняет указанную функцию **бесконечное количество раз с интервалом указанного времени**. Время указывается в миллисекундах, по умолчанию 0. Оба метода могу отдать результат не сразу через указанное время, а с небольшой задержкой, так как результат будет ждать обработки очереди callstack'a.

_Когда они применяются?_

Когда нужно что-то выполнить или проверить через заданное время. Или несколько, и больше раз, с указанным временным интервалом.

_Как можно их отменить?_

При вызове методов они возвращают id. С помощью id можно завершить работу таймера использовав метод clearTimer(timerId), который в качестве параметра принимает id таймера. Для этого обычно таймеру присваивают переменную, которая будет хранить его id.

**Comment by kicumkicum** [comment]
Исчерпывающий ответ. Можно закрывать
